name: Release Library

on:
  release:
    types: [published, created, released]
        tags:
      - "v*"

jobs:
  release:
    name: CD
    runs-on: ubuntu-latest
  
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Update resources
        run: |
          sudo apt-get update -y

      - name: Add g++ 10 for c++ 17 support
        run: |
          sudo apt install gcc-10 g++-10
          sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-10 100 --slave /usr/bin/g++ g++ /usr/bin/g++-10 --slave /usr/bin/gcov gcov /usr/bin/gcov-10
          sudo update-alternatives --set gcc /usr/bin/gcc-10

      - name: Install Doxygen requirements
        run: |
          sudo apt install -y doxygen graphviz
          doxygen --version
          dot -V

      - name: Create executable
        working-directory: .
        run: |
          sudo cmake -Bbuild -DCMAKE_BUILD_TYPE=Release -DDOCS=ON
          sudo make -j8 -C build

      - name: Run ctest
        working-directory: ./build
        run: |
          sudo ctest --verbose
       
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.DEPLOY_TOKEN }}
          publish_dir: ./Docs
      
      - name: Print Deployed URL
        run: |
          echo "Deployed URL: https://${{ github.repository }}.github.io/${{ env.REPO_NAME }}/html"
        env:
          REPO_NAME: ${{ github.repository_name }}
      
      # parse Tag name
      - name: Parse Tag Name
        id: parse_tag
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
      
      # Release version files
      - name: Release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.DEPLOY_TOKEN}}"
          prerelease: false
          automatic_release_tag: ${{ steps.parse_tag.outputs.VERSION }}
